// Codegen: vendor Material Symbols Rounded glyphs as tree-shaken React SVG
// components. Re-run after editing ICON_NAMES:  node scripts/gen-icons.mjs
//
// Source glyphs: @material-symbols/svg-400/rounded/<name>.svg
// Output: src/icons/material-symbols/<name>.tsx + index.ts registry
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, "..");
const SRC = join(web, "node_modules/@material-symbols/svg-400/rounded");
const OUT = join(web, "src/icons/material-symbols");

// Keep in sync with @office/shared REQUEST_TYPE_ICONS + UI_ICONS.
const ICON_NAMES = [
  // request types
  "local_cafe", "tapas", "inventory_2", "print", "handyman", "add_circle",
  // ui
  "check_circle", "forward", "forward_to_inbox", "task_alt", "schedule",
  "priority_high", "location_on", "sticky_note_2", "notifications", "person",
  "groups", "send", "arrow_back", "close", "inbox", "install_desktop",
  "more_horiz", "add", "check", "favorite", "favorite-fill",
  "calendar_today", "arrow_drop_down",
];

const pascal = (s) => s.replace(/(^|[_-])([a-z0-9])/g, (_, __, c) => c.toUpperCase());

mkdirSync(OUT, { recursive: true });

const entries = [];
for (const name of ICON_NAMES) {
  const svgPath = join(SRC, `${name}.svg`);
  if (!existsSync(svgPath)) throw new Error(`Missing glyph: ${name}.svg`);
  const svg = readFileSync(svgPath, "utf8");
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  const Comp = pascal(name);
  const tsx = `import type { SVGProps } from "react";

// Material Symbols Rounded — ${name}. Generated by scripts/gen-icons.mjs.
export function ${Comp}(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 -960 960 960"
      width="1em"
      height="1em"
      fill="currentColor"
      aria-hidden="true"
      {...props}
    >
      ${inner}
    </svg>
  );
}
`;
  writeFileSync(join(OUT, `${name}.tsx`), tsx);
  entries.push({ name, Comp });
}

// Registry maps Material Symbols name -> component (the swap point).
const imports = entries
  .map((e) => `import { ${e.Comp} } from "./${e.name}.js";`)
  .join("\n");
const map = entries.map((e) => `  ${JSON.stringify(e.name)}: ${e.Comp},`).join("\n");
const index = `${imports}

export const ICON_REGISTRY = {
${map}
} as const;

export type IconName = keyof typeof ICON_REGISTRY;
`;
writeFileSync(join(OUT, "index.ts"), index);

console.log(`Generated ${entries.length} icon components in ${OUT}`);
